/*
 *	machdep.h generated by machdep at Mon Sep 30 22:51:06 2019
 */

#ifndef __machdep_h__
#define __machdep_h__

#ifndef EXIT_SUCCESS
#define EXIT_SUCCESS 0
#define EXIT_FAILURE 1
#endif

#define MACH_SHORT_SIZE 2
#define MACH_INT_SIZE 4
#define MACH_LONG_SIZE 8
#define MACH_FLOAT_SIZE 4
#define MACH_DOUBLE_SIZE 8
#define MACH_BYTE_ORDER_LSB_FIRST
#define MACH_BITFIELDS_LSB_FIRST

#endif /* __machdep_h__ */
